version: "3.9"

services:
  backend:
    build: ./backend
    container_name: sql_rag_backend
    ports:
      - "8000:8000"
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY} # pulled from .env in project root
    restart: always

  frontend:
    build: ./frontend
    container_name: sql_rag_frontend
    ports:
      - "3000:80"
    restart: always
