services:
  backend:
    build: ./backend
    container_name: sql_rag_backend
    ports:
      - "8000:8000"
    restart: always

  frontend:
    build: ./frontend
    container_name: sql_rag_frontend
    ports:
      - "3000:80"
    restart: always
